oldRes<-read.table("~/Documents/TargetALS/genesDEres234subjectsTargetALS_site copy.txt",sep="\t",row.names=1,header=TRUE)
head(oldRes)
head(resIHWOrdered,10)
head(oldRes,10)
resFilteredSalmon <- subset(resIHWOrdered, padj < 0.05)
dim(resFilteredSalmon)
resFilteredStar <- subset(oldRes, padj < 0.05)
dim(resFilteredStar)
length(intersect(rownames(resFilteredSalmon),rownames(resFilteredStar)))
rownames(resFilteredSalmon) <- sub("\\..*", "", rownames(resFilteredSalmon))
head(resFilteredSalmon)
length(intersect(rownames(resFilteredSalmon),rownames(resFilteredStar)))
topSalmon<-head(resFilteredSalmon,100))
topSalmon<-head(resFilteredSalmon,100)
topStar<-head(resFilteredStar,100)
length(intersect(rownames(topSalmon),rownames(topStar)))
